version: "3.1"

services:
  uredi_msql_db:
    image: mysql:5.7
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: uredi_msql_db
      MYSQL_ROOT_USER: uredi
      MYSQL_USER: uredi
      MYSQL_ROOT_PASSWORD: secret_pwd
      MYSQL_PASSWORD: secret_pwd
